### ISSUE TITLE
M5Stack Fire LCD color inverted

### ISSUE THREAD

**Issue by k4m454k** [m5stack/M5Stack_MicroPython#14]
Hello
Im flash default config micropython
after `from m5stack import lcd`
Display works, but colors inverted

and..

```
>>> lcd.ptintln("helloworld")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'TFT' object has no attribute 'ptintln'
>>> lcd.ptint("helloworld")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'TFT' object has no attribute 'ptint'
```

**Comment by k4m454k** [comment]
Yes..
Need execute `lcd.tft_writecmd(0x21)` and colors fine)
